links:
  - title: GitHub
    url: https://github.com/thewarpaint/

  - title: LinkedIn
    url: https://www.linkedin.com/in/eduardogarciaesp/

  - title: E-Mail
    url: mailto:eduardogarcia.xyz@gmail.com

  - title: Source code of this page
    url: https://github.com/thewarpaint/eduardogarcia.xyz/blob/master/index.html

jobs:
  - companyName: eSailors
    companyWebsite: https://www.esailors.de/
    title: Software Engineer
    city: Hamburg
    startYear: 2016
    endYear: now

  - companyName: Ooyala
    companyWebsite: https://ooyala.com/
    title: Frontend Team Lead + Senior Frontend Engineer
    city: Guadalajara
    startYear: 2014
    endYear: 2016

  - companyName: Vinco Orbis
    companyWebsite: https://vincoorbis.com/
    title: Project Manager + Full Stack Developer
    city: Mexico City
    startYear: 2010
    endYear: 2014

schools:
  - name: Superior School of Computer Sciences (ESCOM)
    website: http://www.escom.ipn.mx/
    degree: BS in Computer Science, Engineer (undergraduate)

  - name: Instituto Fundaci&oacute;n Azteca
    website: http://www.fundacionazteca.org/Plantel-Azteca
    degree: Computer Technician

projects:
  - name: Caracteres
    url: https://caracteres.io/
    description: >
      A collection of interesting letters, symbols, ligatures, etc. present in languages that share the
      Roman alphabet.

  - name: Trumpmit
    url: https://thewarpaint.github.io/trumpmit/
    description: >
      Make Git Commit Messages Great Again!

  - name: Geometry Club web app
    url: https://eduardogarcia.xyz/geometry-club
    description: >
      A proof-of-concept web app for <A HREF="https://geometryclub.org/">the Geometry Club project.

  - name: Hyperlogout
    url: http://thewarpaint.github.io/hyperlogout/
    description: >
      A website that will log you out from popular internet services that <EM>probably</EM> implement logout
      in an unsafe way.

  - name: Days without a new Adam Sandler movie dot com
    url: http://thewarpaint.github.io/dayswithoutanewadamsandlermovie.com/
    description: >
      We all wish the counter would just keep going, but sadly, time and time again it breaks our hearts and
      goes back to zero.

languages:
  - name: Spanish
    level: native

  - name: English
    level: intermediate

  - name: Italian
    level: basic

  - name: German
    level: I can order food and most of the times I get what I wanted
