version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1

    working_directory: ~/eduardogarcia-xyz

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "33:1d:c9:c1:cc:0a:fd:bf:d7:51:a7:bc:4f:cd:d9:e3"

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Configure git user info
          command: |
            git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
            git config --global user.name "$GH_NAME" > /dev/null 2>&1

      - deploy:
          name: Publish static website
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/publish.sh
            fi
